[package]
name = "rust_cpp_text_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.177"

[build-dependencies]
cc = "1.2.41" 
# Note: extern "C" works without the `cc` crate.
# `cc` is only needed if I want Cargo to compile and link C/C++ sources automatically.
